import numpy as np
marks=np.array([[80,89,78,0,75],[78,0,87,0,85],[89,85,90,95,99]])
print("initial",marks)
print("---------")
good_students = marks[np.all(marks > 80, axis=1)]
print(good_students)
print("---------")
xero=marks==0
# Convert the array to float type before assigning np.nan
marks = marks.astype(float)
marks[xero]=np.nan
print("after adding nan on zero",marks)
print("---------")
avg_column=np.nanmean(marks,axis=0)
print("average of all columns",avg_column)
nan_indices=np.where(np.isnan(marks))
print("------")
print("indices of nan",nan_indices)
avg_value_replace_nan=np.take(avg_column,nan_indices[1])
print("------")
print("column averages where nan is situated",avg_value_replace_nan)
marks[nan_indices]=avg_value_replace_nan
print("------")
print("avg values replaced from nan",marks)
oneD_array=marks.flatten()
print("------")
print("1D array",oneD_array)
avg_marks=np.mean(oneD_array)
print("------")
print("average of 1D array",avg_marks)
max_marks=np.max(oneD_array)
print("------")
print("maximum marks",max_marks)
min_marks=np.min(oneD_array)
print("------")
print("minimum marks",min_marks)
std_marks=np.std(oneD_array)
print("------")
print("standard deviation",std_marks)
